# Generated by Django 5.1.6 on 2025-03-09 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('contador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseSWOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('opportunities', models.TextField()),
                ('threats', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('texto', 'Resposta Textual'), ('multipla', 'Múltipla Escolha'), ('swot', 'Classificação SWOT')], max_length=20)),
                ('categoria_swot', models.CharField(blank=True, max_length=15, null=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='SWOTResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.pergunta')),
            ],
            options={
                'unique_together': {('formulario', 'pergunta')},
            },
        ),
    ]
