# Generated by Django 5.1.6 on 2025-02-27 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SWOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forca', models.CharField(max_length=255)),
                ('fraqueza', models.CharField(max_length=255)),
                ('oportunidade', models.CharField(max_length=255)),
                ('ameaca', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='relatorio',
            old_name='pontos_fortes',
            new_name='conteudo',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='pontos_fracos',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='recomendacoes',
        ),
        migrations.RemoveField(
            model_name='respostaformulario',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='respostaformulario',
            name='pergunta',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='titulo',
            field=models.CharField(default='Relatório Padrão', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='respostaformulario',
            name='formulario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario'),
            preserve_default=False,
        ),
    ]
