# Generated by Django 5.1.6 on 2025-02-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_swot_rename_pontos_fortes_relatorio_conteudo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swot',
            old_name='ameaca',
            new_name='ameacas',
        ),
        migrations.RenameField(
            model_name='swot',
            old_name='forca',
            new_name='forcas',
        ),
        migrations.RenameField(
            model_name='swot',
            old_name='fraqueza',
            new_name='fraquezas',
        ),
        migrations.RenameField(
            model_name='swot',
            old_name='oportunidade',
            new_name='oportunidades',
        ),
        migrations.AddField(
            model_name='swot',
            name='cnpj',
            field=models.CharField(default='00.000.000/0000-00', max_length=18),
            preserve_default=False,
        ),
    ]
