# Generated by Django 5.1.6 on 2025-02-27 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_rename_ameaca_swot_ameacas_rename_forca_swot_forcas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='respostaformulario',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='swot',
            name='cnpj',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='formulario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='pontos_fortes',
            field=models.TextField(default='Pontos fortes...'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='pontos_fracos',
            field=models.TextField(default='Pontos fracos...'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='recomendacoes',
            field=models.TextField(default='Recomendações...'),
        ),
        migrations.AddField(
            model_name='swot',
            name='formulario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respostaformulario',
            name='resposta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='swot',
            name='ameacas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='swot',
            name='forcas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='swot',
            name='fraquezas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='swot',
            name='oportunidades',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario')),
            ],
        ),
        migrations.AddField(
            model_name='respostaformulario',
            name='pergunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formulario.pergunta'),
        ),
    ]
